# Generated by Django 5.2.1 on 2025-05-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_admins_adminnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admins',
            name='adminnumber',
            field=models.IntegerField(),
        ),
    ]
